[package]
name = "overwrite-ring-buffer"
version = "0.18.0"
edition = "2024"
description = "A fixed-size and resizable overwrite ring buffer for Rust."
license = "MIT"
repository = "https://github.com/Tokeiya/overwrite-ring-buffer"
keywords = ["ring-buffer", "circular-buffer", "buffer"]
categories = ["data-structures"]
[dev-dependencies]
rand = "0.10.1"
rand_chacha = "0.10.0"

[dependencies]
thiserror = "2.0.18"